nanoframework/nanoFramework.Runtime.Native

- source/Nuget.nanoFramework.Runtime.Native.DELIVERABLES/Nuget.nanoFramework.Runtime.Native.DELIVERABLES.nuproj
- source/Nuget.nanoFramework.Runtime.Native/Nuget.nanoFramework.Runtime.Native.nuproj
- source/Properties/AssemblyInfo.cs
- source/nanoFramework.Runtime.Native.nfproj
- source/packages.config
- Update version info to 1.0.0.0
- Add AssemblyInformationalVersion attribute
- Update dependency
- Add dependency to Nuget deliverables
> Update corlib reference

- appveyor.yml
- install-vsix-appveyor.ps1
- source/Nuget.nanoFramework.Runtime.Native.DELIVERABLES/Nuget.nanoFramework.Runtime.Native.DELIVERABLES.nuproj
- source/Nuget.nanoFramework.Runtime.Native/Nuget.nanoFramework.Runtime.Native.nuproj
- source/nanoFramework.Runtime.Native.Nuget.sln
- source/nanoFramework.Runtime.Native.nfproj
- source/nanoFramework.Runtime.Native.sln
- source/packages.config
- Extracted Nuget build project to separate solution
- Update AppVeyor accordingly
- Update readme to show more details and correct build/download badges
- Correct download URL for VS extension
- Update Nuget refs
> Extracted Nuget build project to separate solution

- appveyor.yml
- source/ExecutionConstraint.cs
- source/Hardware/SystemInfo.cs
- source/Nuget.nanoFramework.Runtime.Native.DELIVERABLES/Nuget.nanoFramework.Runtime.Native.DELIVERABLES.nuproj
- source/Nuget.nanoFramework.Runtime.Native/Nuget.nanoFramework.Runtime.Native.nuproj
- source/nanoFramework.Runtime.Native.nfproj
- source/packages.config
- Revert DateTime package (now it's back in mscorlib)
- Correct typos
> Revert DateTime package (now it's back in mscorlib)

- source/RTC.cs
- source/nanoFramework.Runtime.Native.nfproj
- Add RTC class 
- Provides managed API to set RTC and alarm
> Add RTC class

- source/Nuget.nanoFramework.Runtime.Native.DELIVERABLES/Nuget.nanoFramework.Runtime.Native.DELIVERABLES.nuproj
- source/Nuget.nanoFramework.Runtime.Native/Nuget.nanoFramework.Runtime.Native.nuproj
- source/nanoFramework.Runtime.Native.nfproj
- source/packages.config
- Update mscorlib package
- Also correct project URL for Nuget deliverables project
Signed-off-by: josesimoes <jose.simoes@eclo.solutions>
> Update mscorlib package

- source/Power.cs
- source/nanoFramework.Runtime.Native.nfproj
- Add API to reboot target device
- Addresses nanoFramework/Home#349
> Add Power API

- source/SystemInfo.cs
- Addresses nanoFramework/Home#355
> Correct typo in method name

- source/ResourceUtility.cs
- source/nanoFramework.Runtime.Native.nfproj
- Add support for ResourceUtility class in nanoFramework.Runtime.Native. Allows access to managed app resources.
> Add new class ResourceUtility

- source/nanoFramework.Runtime.Native/ResourceUtility.cs
> Fix exception in ResourceUtility constructor

- source/nanoFramework.Runtime.Native/ExecutionConstraint.cs
- Improve documentation for ExecutionConstraint.
- Also renamed parameter to improve clarity.
> Improve documentation for ExecutionConstraint

- source/nanoFramework.Runtime.Native/Properties/AssemblyInfo.cs
- source/nanoFramework.Runtime.Native/SystemInfo.cs
- Add Platform and TargetName to SystemInfo class.
- Bump AssemblyNativeVersion version to 1.0.5.0.
- Closes nanoFramework/Home#414.
- Native sample from samples repo.
> Add Platform and TargetName to SystemInfo class

- source/nanoFramework.Runtime.Native/Properties/AssemblyInfo.cs
- source/nanoFramework.Runtime.Native/nanoFramework.Runtime.Native.nfproj
- Add exclusion of ThisAssembly class (from Nerdbank.GitVersioning).
- Bump version of native assembly.
- Addresses nanoframework/Home#485.
- Addresses nanoframework/Home#491.
> Work on native assembly declaration

- source/nanoFramework.Runtime.Native/Debug.cs
- Improve comment on Debug.GC.
- Parameter description was wrong. It's actually meant to request GC to execute heap compaction.
> Improve comment on Debug.GC

- source/nanoFramework.Runtime.Native/GC.cs
- source/nanoFramework.Runtime.Native/Properties/AssemblyInfo.cs
- source/nanoFramework.Runtime.Native/nanoFramework.Runtime.Native.nfproj
- source/version.json
- Rename GC method ot Run.
- Update comments accordingly.
- Bump AssemblyNativeVersion to 100.0.8.0.
- Bump version to 1.4.0-preview.
- Remove duplication of Debug class in System.Diagnostics and nanoFramework.Runtime.Native.
Signed-off-by: josesimoes <jose.simoes@eclo.solutions>
> Rename Debug class to GC

- nanoFramework.Runtime.Native/nanoFramework.Runtime.Native.nfproj
Work on https://github.com/nanoframework/Home/issues/817
> Remove NFMDP_PE_LoadHints from nfproj

- nanoFramework.Runtime.Native/Properties/AssemblyInfo.cs
- nanoFramework.Runtime.Native/System/Environment.cs
- nanoFramework.Runtime.Native/nanoFramework.Runtime.Native.nfproj
- version.json
- Bump AssemblyNativeVersion 100.0.9.0.
- Bump version to 1.5.4-preview.
- Resolves nanoFramework/Home#943.
> Add Environment.TickCount64

- .github/workflows/pr-checks.yml
- .github/workflows/update-dependencies.yml
- README.md
- nanoFramework.Runtime.Native/nanoFramework.Runtime.Native.nfproj
- nanoFramework.Runtime.Native/packages.config
- nanoFramework.Runtime.Native/packages.lock.json
- Add/update github actions.
- Add packages lock file.
- Update tools version.
- Update readme.
- Addresses  nanoFramework/Home#1163.
- Addresses  nanoFramework/Home#1162.
> Work CI-CD

- nanoFramework.Runtime.Native/ExecutionConstraint.cs
- nanoFramework.Runtime.Native/GC.cs
- nanoFramework.Runtime.Native/Power.cs
- nanoFramework.Runtime.Native/Properties/AssemblyInfo.cs
- nanoFramework.Runtime.Native/RTC.cs
- nanoFramework.Runtime.Native/System/Environment.cs
- nanoFramework.Runtime.Native/SystemInfo.cs
- Fix code style in several classes.
- Fix license headers in all source files.
- Add pragma declarations where needed.
- Fix order of method modifiers.
> Miscellaneous code style fixes

- nanoFramework.Runtime.Native/ExecutionConstraint.cs
- nanoFramework.Runtime.Native/GC.cs
- nanoFramework.Runtime.Native/Power.cs
- nanoFramework.Runtime.Native/RTC.cs
- nanoFramework.Runtime.Native/System/Environment.cs
- nanoFramework.Runtime.Native/SystemInfo.cs
- Improve Intellisense comments throughout the code base.
> Improve Intellisense comments throughout the code base

- nanoFramework.Runtime.Native.nuspec
- nanoFramework.Runtime.Native/nanoFramework.Runtime.Native.nfproj
- nanoFramework.Runtime.Native/packages.config
- nanoFramework.Runtime.Native/packages.lock.json
- Update mscorlib to 2.0.0-preview.17
> Update mscorlib to 2.0.0-preview.17
